### ISSUE TITLE
Saving tags to an image asset crashes studio

### ISSUE THREAD

**Issue by roffelsaurus** [sanity-io/sanity-plugin-media#81]
1. Either have a ready tag or make it inline in the Individual asset view.
2. Select the tag on the asset, click save
3. React loop detection massive crash

Nevertheless, the tag is persisted to the asset as it becomes a search result under the tag. 

However, attempting to edit the asset now leads to a similar looking stack trace crash.

sanity-plugin-media 1.4.9
sanity stuff 2.30.1 (latest as of today)

I'm not sure the stack trace is very helpful, but the error seems to be an infinite loop on state changes and hooks/lifecycle methods in the react-select library.

Stack trace:
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (/static/js/vendor.bundle.js:26235:15)
    at scheduleUpdateOnFiber (/static/js/vendor.bundle.js:24306:3)
    at dispatchAction (/static/js/vendor.bundle.js:18802:5)
    at Object.set (/static/js/app.bundle.js:67509:25)
    at http://localhost:3333/static/js/app.bundle.js:66489:23
    at registerFieldRef (/static/js/app.bundle.js:66869:17)
    at register (/static/js/app.bundle.js:66900:17)
    at http://localhost:3333/static/js/app.bundle.js:67503:13
    at http://localhost:3333/static/js/app.bundle.js:67533:9
    at commitHookEffectListMount (/static/js/vendor.bundle.js:22873:26)

The above error occurred in the <Controller> component:
    in Controller (created by FormFieldInputTags)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by FormFieldInputTags)
    in FormFieldInputTags (created by DialogAssetEdit)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Stack))
    in ForwardRef(Stack) (created by DialogAssetEdit)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by ForwardRef(TabPanel))
    in ForwardRef(TabPanel) (created by DialogAssetEdit)
    in form (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by DialogAssetEdit)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by DialogAssetEdit)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Flex))
    in ForwardRef(Flex) (created by DialogAssetEdit)
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(DialogCard))
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Flex))
    in ForwardRef(Flex) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(DialogCard))
    in div (created by styled.div)
    in styled.div (created by ForwardRef(Box))
    in ForwardRef(Box) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(Card))
    in Fe (created by ThemeProvider)
    in ThemeProvider (created by ThemeColorProvider)
    in ThemeColorProvider (created by ForwardRef(Card))
    in ForwardRef(Card) (created by Styled(Component))
    in Styled(Component) (created by ForwardRef(DialogCard))
    in div (created by styled.div)

**Comment by roffelsaurus** [comment]
Upon more investigation, 
Fixing version to 1.4.8 fixes this issue, so I would guess the offender is somewhere in here
https://github.com/robinpyon/sanity-plugin-media/compare/v1.4.8...v1.4.9
